version: '3.8'

services:
  mini-g-platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-g-robotics-platform
    restart: unless-stopped
   # ports:
    #  - "80:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
